# Generated by Django 5.0.1 on 2024-02-27 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('item_id', models.AutoField(primary_key=True, serialize=False)),
                ('item_name', models.CharField(max_length=200)),
                ('item_description', models.CharField(max_length=1000)),
                ('item_price', models.FloatField()),
                ('item_rating', models.IntegerField(blank=True)),
                ('item_reviews', models.CharField(blank=True, max_length=5000)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_age', models.IntegerField()),
                ('card_number', models.IntegerField()),
                ('is_admin', models.BooleanField(default=False)),
                ('username', models.CharField(max_length=200)),
                ('user_pass', models.CharField(max_length=50)),
                ('user_email', models.CharField(max_length=100)),
                ('user_first', models.CharField(max_length=100)),
                ('user_last', models.CharField(max_length=100)),
            ],
        ),
    ]
